#!/bin/sh
#

SYSLOGD_ARGS=-n
KLOGD_ARGS=-n

BENCHMARK=429.mcf

start() {
	echo "Starting $BENCHMARK"
	/root/hpm_counters & root/run.sh
	killall hpm_counters
	echo "Finishing $BENCHMARK"
	poweroff
}

case "$1" in
  start)
	start
	;;
  stop)
	#stop
	;;
  restart|reload)
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
