#!/bin/sh
#
# Start the network....
#

# Debian ifupdown needs the /run/network lock directory
mkdir -p /run/network

case "$1" in
  start)
        mac=$(ifconfig | grep -o "..:..:..:..:..:..")
        machigh=$(echo $mac | cut -c 13-14 -)
        maclow=$(echo $mac | cut -c 16-17 -)
        macbig=$machigh$maclow
        case "$macbig" in
        0002 | 0003 | 0004 | 0005)
            poweroff
            ;;
        *)
            echo "continuing"
            ;;
        esac
	;;
  stop)
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

